name: Markdown Check

on:
  push:
    paths:
      - "**.md"
  pull_request:
    paths:
      - "**.md"

jobs:
  markdown-files-exist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Confirm Markdown files exist
        run: |
          echo "checking repository documentation..."
          find . -name "*.md" -print
